- name: Configuring YUM repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Configure YUM Repos for RabbitMQ
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Installing RabbitMQ server 
  ansible.builtin.package:
    name: rabbitmq-server
    state: present 

- name: Enable and Stating RabbitMQ 
  ansible.builtin.service:
    name: rabbitmq-server
    enabled: yes 
    state: started 

- name: Creating Roboshop credentials
  ansible.builtin.shell: "rabbitmqctl add_user {{rq_user}} {{rq_password}}"

- name: Setting up the permissions for Roboshop User 
  ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"