- name: Installing mysql server
  ansible.builtin.package:
    name: mysql-server
    state: present 

- name: Enable and Starting mysql
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started

- name: changing the default root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1