- name: Configuring app-setup
  ansible.builtin.import_role:
    name: common 
    tasks_from: app-setup.yaml

- name: Configuring golang-setup
  ansible.builtin.import_role:
    name: common 
    tasks_from: golang-setup.yaml

- name: Configuring systemd-setup
  ansible.builtin.import_role:
    name: common 
    tasks_from: systemd-setup.yaml 