- name: Creating roboshop user
  ansible.builtin.user:
    name: roboshop 

- name: Recursively removing /app directory 
  ansible.builtin.file:
    path: /app
    state: absent 

- name: Creating /app directory 
  ansible.builtin.file:
    path: /app 
    state: directory

- name: "Downoloading the {{component}}.zip"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp 

- name: "Unzipping {{component}}.zip"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    remote_src: yes 
    dest: /app 
