- name: Installing golang 
  ansible.builtin.dnf:
    name: golang 
    state: present 

- name: Installing dependecies 
  ansible.builtin.command: "{{item}}"
  loop:
    - go mod init dispatch
    - go get 
    - go build
  args:
    chdir: /app