- name: Installing mysql client 
  ansible.builtin.dnf: 
    name: mysql
    state: present 

- name: Check cities schema exist or not 
  ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: cities_schema 

- name: Print Cities Schema output 
  ansible.builtin.debug:
    msg: "Cities Scehma Output is {{cities_schema}}"

- name: Loading cities data 
  ansible.builtin.shell: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/db/schema.sql
  when: cities_schema.stdout == "0"

- name: Loading App user data 
  ansible.builtin.shell: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/db/app-user.sql
  when: cities_schema.stdout == "0"

- name: Loading Master data 
  ansible.builtin.shell: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/db/master-data.sql
  when: cities_schema.stdout == "0"